## UNIVERSIDAD GALILEO
## MAESTRIA EN DATA SCIENCE
## CIENCIA DE DATOS EN PYTHON

### Luis Alejandro Samayoa
### 19002957

## Investigacion np.darray y np.matrix

## Diferencias entre np.darray y np.matrix

Las matrices en numpy son representaciones multidimensionales de vectores al igual que np.darray. Muchas de las operaciones que se pueden realizar tanto para matrices como para darrays.

In [15]:
import numpy as np
x=np.array([[2, 1], [2, 3]])
y=np.matrix([[2, 1], [2, 3]])
print(x+y)
print(x+x)
print(y+y)

[[4 2]
 [4 6]]
[[4 2]
 [4 6]]
[[4 2]
 [4 6]]


En ambos casos es posible calcular la transpuesta 

In [11]:
print(x.T)
print(y.T)

[[2 2]
 [1 3]]
[[2 2]
 [1 3]]


No es posible realizar multiplicacion vectorial con arrays multidimensionales, unicamente con arreglos tipo matriz. Con array multiplica elemento por elemento.

In [18]:
x*x

array([[4, 1],
       [4, 9]])

In [19]:
y*y

matrix([[ 6,  5],
        [10, 11]])

Otra de las ventajas del arrego matriz, es que la inversa unicamente es posible calcularla con arreglos tipos matriz, no con darrays.

In [16]:
print(x.I)

AttributeError: 'numpy.ndarray' object has no attribute 'I'

In [17]:
print(y.I)

[[ 0.75 -0.25]
 [-0.5   0.5 ]]


## Conclusion
Ambos tipos de arreglos son parecedios, pero las operaciones necesarias para trabajar con matrices unicamente se pueden realizar con arreglos tipo matriz. En ese sentido, tiene ventajas sobre los arrays multidimensionales.

## Fuente:
https://stackoverflow.com/questions/4151128/what-are-the-differences-between-numpy-arrays-and-matrices-which-one-should-i-u/15406440